# Generated by Django 4.2.6 on 2023-10-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(null=True, upload_to='hotel_images')),
                ('description', models.TextField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('person_place', models.CharField(max_length=50, null=True)),
                ('time_input', models.DateField()),
                ('time_output', models.DateField()),
                ('bath', models.BooleanField(default=True)),
                ('car', models.BooleanField(default=True)),
                ('bar', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('sport', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Myhmanhana',
                'verbose_name_plural': 'Myhmanhanalar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('male', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ulanyjy',
                'verbose_name_plural': 'Ulanyjylar',
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(upload_to='hotel_images')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Suratlar',
            },
        ),
        migrations.CreateModel(
            name='Hotel_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('male', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
            options={
                'verbose_name': 'Myhmanhana dolandyryjysy',
                'verbose_name_plural': 'Myhmanhana dolandyryjylary',
            },
        ),
    ]
