# Generated by Django 4.2.6 on 2023-10-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price',
            new_name='vr_url',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='url',
            new_name='web_url',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='bath',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='car',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='person_place',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='time_input',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='time_output',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='wifi',
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('vr_url', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(null=True, upload_to='room_images')),
                ('description', models.TextField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('person_place', models.CharField(max_length=50, null=True)),
                ('bath', models.BooleanField(default=True)),
                ('car', models.BooleanField(default=True)),
                ('bar', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('sport', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
            options={
                'verbose_name': 'Otag',
                'verbose_name_plural': 'Otaglar',
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(null=True, upload_to='meals_images')),
                ('description', models.TextField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
            options={
                'verbose_name': 'Tagam',
                'verbose_name_plural': 'Tagamlar',
            },
        ),
    ]
