# Generated by Django 4.2.6 on 2023-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_price_hotel_vr_url_rename_url_hotel_web_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='vip',
            field=models.BooleanField(default=True),
        ),
    ]
