# Generated by Django 4.2.6 on 2023-10-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hotel_phone_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='hotel',
        ),
        migrations.AddField(
            model_name='favorite',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='img',
            field=models.ImageField(null=True, upload_to='hotel_images'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vr_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='web_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
