# Generated by Django 4.2.6 on 2023-10-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_favorite_hotel_favorite_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='vr_url',
            field=models.ImageField(null=True, upload_to='room_images/vr'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='vr_url',
            field=models.ImageField(null=True, upload_to='room_images/vr'),
        ),
    ]
