# Generated by Django 4.2.6 on 2023-10-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_hotel_vr_url_alter_rooms_vr_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("room_id", models.IntegerField()),
                ("phone", models.CharField(max_length=11, null=True)),
                ("description", models.TextField(null=True)),
                ("add_date", models.DateField()),
                ("created", models.DateField(auto_now_add=True)),
                ("checked", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sargyt",
                "verbose_name_plural": "Sargytlar",
            },
        ),
    ]
