# Generated by Django 4.2.6 on 2023-10-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_hotel_vr_url_remove_rooms_vr_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AlterField(
            model_name="orders",
            name="add_date",
            field=models.DateField(verbose_name="Sargyt edilmeli wagty"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.CharField(max_length=255, null=True, verbose_name="Salgysy"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="author",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sargyt eden"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="checked",
            field=models.BooleanField(default=True, verbose_name="Kabul edildi"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="description",
            field=models.TextField(null=True, verbose_name="Maglumaty"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.hotel",
                verbose_name="Myhmanhana",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="room_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.rooms",
                verbose_name="Otagy",
            ),
        ),
    ]
