# Generated by Django 4.2.6 on 2023-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_delete_favorite_delete_user_alter_orders_add_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="back_date",
            field=models.DateField(null=True, verbose_name="Sargyt edilmeli wagty"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="description",
            field=models.TextField(null=True, verbose_name="Maglumaty"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="img",
            field=models.ImageField(
                null=True, upload_to="hotel_images", verbose_name="Suraty"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="phone",
            field=models.CharField(
                max_length=11, null=True, verbose_name="Telefon belgisi"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="vip",
            field=models.BooleanField(default=True, verbose_name="Vip otag"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="web_url",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Web salgysy"
            ),
        ),
    ]
